ALTER TABLE posts ADD COLUMN views_count INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS likes (
    post_id INTEGER NOT NULL,
    author_account_id INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    PRIMARY KEY (post_id, author_account_id)
);

CREATE TABLE IF NOT EXISTS outbox (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    is_processed BOOLEAN NOT NULL DEFAULT FALSE,
    event_type VARCHAR(64) NOT NULL,
    payload JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE TRIGGER on_outbox_update
BEFORE UPDATE ON outbox
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
