services:
  gateway:
    build:
      dockerfile: ${PWD}/services/gateway/Dockerfile
    container_name: gateway-service
    depends_on:
      - accounts
    environment:
      GATEWAY_SERVICE_PORT: ${GATEWAY_SERVICE_PORT}
      JWT_ED25519_PUBLIC_KEY: ${JWT_ED25519_PUBLIC_KEY}
    ports:
      - "${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}"
  
  accounts-postgres:
    image: postgres:17-alpine
    container_name: accounts-postgres
    environment:
      POSTGRES_USER: ${ACCOUNTS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ACCOUNTS_POSTGRES_PASSWORD}
      POSTGRES_DB: accounts-postgres
    volumes:
      - ${PWD}/services/accounts/db/migrations:/docker-entrypoint-initdb.d
      - ${ACCOUNTS_POSTGRES_DATA}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --username ${ACCOUNTS_POSTGRES_USER} --dbname accounts-postgres
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  accounts:
    build:
      dockerfile: ${PWD}/services/accounts/Dockerfile
    container_name: accounts-service
    depends_on:
      - accounts-postgres
    environment:
      ACCOUNTS_SERVICE_PORT: ${ACCOUNTS_SERVICE_PORT}
      DB_HOST: "accounts-postgres"
      DB_USER: ${ACCOUNTS_POSTGRES_USER}
      DB_PASSWORD: ${ACCOUNTS_POSTGRES_PASSWORD}
      DB_POOL_SIZE: 5
      JWT_ED25519_PRIVATE_KEY: ${JWT_ED25519_PRIVATE_KEY}
