openapi: 3.1.0
info:
  title: Gateway API
  version: 1.0.0
servers:
- url: /
paths:
  /profile:
    post:
      summary: Зарегестрировать новый профиль
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterProfileRequest"
      responses:
        "200":
          description: Профиль успешно создан
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterProfileResponse"
        "400":
          description: Инвалидные значения полей профиля
  /profile/{id}:
    get:
      summary: Получить данные профиля
      parameters:
      - name: id
        in: path
        description: уникальный id профиля
        required: true
        style: simple
        explode: false
        schema: {}
      responses:
        "200":
          description: Информация о профиле успешно получена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetProfileResponse"
        "401":
          description: Пользователь не авторизован
        "404":
          description: Профиль с указанным id не найден
    put:
      summary: Изменить данные профиля
      parameters:
      - name: id
        in: path
        description: уникальный id профиля
        required: true
        style: simple
        explode: false
        schema: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EditProfileRequest"
      responses:
        "200":
          description: Информация о профиле успешно изменена
        "400":
          description: Инвалидные новые значения полей профиля
        "401":
          description: Пользователь не авторизован
        "403":
          description: У пользователя недостаточно прав для изменения профиля
        "404":
          description: Профиль с указанным id не найден
    delete:
      summary: Удалить профиль
      parameters:
      - name: id
        in: path
        description: уникальный id профиля
        required: true
        style: simple
        explode: false
        schema: {}
      responses:
        "200":
          description: Профиль удален
        "401":
          description: Пользователь не авторизован
        "403":
          description: У пользователя недостаточно прав для удаления профиля
        "404":
          description: Профиль с указанным id не найден
components:
  schemas:
    RegisterProfileRequest:
      properties:
        login: {}
        password: {}
        email: {}
        phone_number: {}
        name: {}
        surname: {}
    RegisterProfileResponse:
      properties:
        profile_id: {}
      example:
        profile_id: ""
    GetProfileResponse:
      properties:
        name: {}
        surname: {}
        birthday: {}
        bio: {}
      example:
        birthday: ""
        surname: ""
        name: ""
        bio: ""
    EditProfileRequest:
      properties:
        name: {}
        surname: {}
        birthday: {}
        bio: {}
        phone_number: {}
        email: {}
