@startuml

hide circle
skinparam linetype ortho

entity account {
    * id: integer
    --
    * login: varchar
    * password: varchar
    * email: varchar
    phone_number: varchar
    created_at: timestamp
}

entity profile {
    * id: integer
    * account_id: integer
    --
    * name: varchar
    * surname: varchar
    * profile_id: varchar
    birthday: date
    bio: varchar
    updated_at: timestamp
}

entity api_tokens {
    * id: integer
    * account_id: integer
    --
    * token: varchar
    created_at: timestamp
    valid_until: timestamp
    read_access: boolean
    write_access: boolean
}

account ||--o{ api_tokens : has
account ||--|| profile : has

@enduml