@startuml

hide circle
skinparam linetype ortho

entity posts_views {
    * post_id: Int32
    * viewer_account_id: Int32
    * view_time: DateTime
}

entity posts_likes {
    * post_id: Int32
    * liker_account_id: Int32
    * like_time: DateTime
}

entity posts_comments {
    * post_id: Int32
    * author_account_id: Int32
    * comment_id: Int32
    * post_time: DateTime
}

entity registrations {
    * account_id: Int32
    * profile_id: String
    * register_time: DateTime
}

entity posts {
    * post_id: Int32
    * author_id: Int32
    * post_time: DateTime
}

entity agg_post_metrics {
    * post_id: Int32
    * metric: LowCardinality(String)
    * cnt: AggregateFunction(count, UInt64)
}

@enduml
